name: ci-workflow

on:
  push:
    branches:
      - mucho
      - dev
  pull_request:
    branches:
      - mucho
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run build

      # check if build is successful
      - name: List contents of dist directory
        run: find dist/
