name: ci-workflow

on:
  push:
    branches:
      - mucho
      - dev
  pull_request:
    branches:
      - mucho
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
      - uses: actions/setup-node@v2
        with:
          node-version: "17.x"

      # check if build is successful
      - name: List contents of dist directory
        run: find dist/
